name: Build Installer ISO

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04-arm

    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main

      - name: Build Installer
        run: |
          nix build .#installer-iso
          cp result/iso/*.iso $(basename result/iso/*.iso | sed s/aarch64-linux/surface-pro-11-${{ github.ref_name }}/)

      - uses: actions/upload-artifact@v4
        with:
          name: installer
          path: ./*.iso

